config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers:{
    sessions: 'admin_users/sessions',
    registrations: 'admin_users/registrations',
    passwords: 'admin_users/passwords'
  }
  root 'welcome#index'
  get 'welcome/about'
  get '/about' => 'welcome#about'




  resources :projects
  # resources :courses
  # resources :students

  namespace :admin do
    resources :students
    resources :courses
    get 'dashboard' => 'dashboard#index'
  end





end

app/models/student.rb
class Student < ApplicationRecord
  has_many :blogs
  has_and_belongs_to_many :courses
  has_many :student_projects
  has_many :projects, through: :student_projects
  validates :first_name, :last_name, :email, :adress, presence: true
  paginates_per 2
  has_one_attached :profile_image

  validates :email, uniqueness: true
  # validates :date_of_birth, presence: true, numericality: true

  after_save :display_student_age

  def display_student_age
    if self.date_of_birth.present?
      age= Date.today.year - self.date_of_birth.year
      puts "========== Age of the student is #{age} =========="
    else
      puts "========== Age can not be calculated without date_of_birth =========="
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def age
    if self.date_of_birth.present?
      "#{Date.today.year - self.date_of_birth.year}"
    else
      "= Age can not be calculated without date_of_birth ="
    end
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < AdminController


  before_action :set_student, only: %i[show edit update destroy]
  helper_method :formatted_date

  def index
    @students= Student.all.page(params[:page])
  end

  def new
    @student= Student.new
  end

  def create
    @student = Student.new(student_params)
     if @student.save
      redirect_to admin_students_path, notice: 'Student has been created succesfully'
     else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to admin_student_path,notice: 'Student has been updated succesfully'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to admin_students_path, notice: 'Student has been deleted succesfully'
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :adress, :date_of_birth, :contact)
  end

  def set_student
    @student = Student.find(params[:id])
    #select * from students where id=? params[:id]
  end

  def formatted_date(date)
    date.strftime("%d-%m-%Y") if date.present?
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  layout 'admin'

  before_action :set_student, only: %i[show edit update destroy]
  helper_method :formatted_date

  def index
    @students= Student.all
  end

  def new
    @student= Student.new
  end

  def create
    @student = Student.new(student_params)
     if @student.save
      redirect_to students_path, notice: 'Student has been created succesfully'
     else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to student_path,notice: 'Student has been updated succesfully'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path, notice: 'Student has been deleted succesfully'
  end

  private

  def student_params
    params.permit(:first_name, :last_name, :email, :adress, :date_of_birth, :contact,:profile_image)
  end

  def set_student
    @student = Student.find(params[:id])
    #select * from students where id=? params[:id]
  end

  def formatted_date(date)
    date.strftime("%d-%m-%Y") if date.present?
  end

end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>

    <% if student.errors.any? %>
        <div style="color: red">
            <h2>
                <%= pluralize(student.errors.count, "error" ) %> prohibited this course from being saved:
            </h2>

            <ul>
                <% student.errors.each do |error| %>
                    <li>
                        <%= error.full_message %>
                    </li>
                    <% end %>
            </ul>
        </div>
        <% end %>

            <div class="form-group">
                <%= form.label :first_name %> <br>
                    <%= form.text_field :first_name, class: "form-control form-control-lg" %>
            </div>

            <div class="form-group">
                <%= form.label :last_name %> <br>
                    <%= form.text_field :last_name , class: "form-control form-control-lg"%>
            </div>

            <div class="form-group">
                <%= form.label :email %> <br>
                    <%= form.email_field :email ,class: "form-control form-control-lg"%>
            </div>

            <div class="form-group">
                <%= form.label :adress %> <br>
                    <%= form.text_field :adress,class: "form-control form-control-lg" %>
            </div>

            <div class="form-group">
                <%= form.label :date_of_birth %> <br>
                    <%= form.date_field :date_of_birth,class: "form-control form-control-lg" %>
            </div>

            <div class="form-group">
                <%= form.label :contact %> <br>
                    <%= form.telephone_field :contact,class: "form-control form-control-lg" %>
            </div>
            <br>
            <div class="form-group">
                <%= form.submit class: "btn btn-primary btn-lg" %>
            </div>
            <% end %>

app/views/students/edit.html.erb
<div class="col-lg-8" >
    <h1>Edit Student</h1>

    <%= render "form" , student: @student %>
</div>

app/views/students/index.html.erb
<div class="col-lg-10">
    <p>
        <%= notice %>
    </p>

    <h1>Listing Students</h1>

    <%= link_to 'New Student' , new_student_path, class: "btn btn-primary btn-sm" %>


        <table class="table table-bordered" style="text-align: center;">
            <thead>
                <tr>

                    <th>Student</th>
                    <th>Email</th>
                    <th>Adres</th>
                    <th>Date Of Birth</th>
                    <th colspan="3">Actions</th>
                </tr>
            </thead>

            <tbody>
                <% @students.each do |student| %>
                    <tr>
                        <td style="text-align: left;">
                            <%= student.full_name %>
                        </td>

                        <td >
                            <%= student.email%>
                        </td>

                        <td>
                            <%= student.adress %>
                        </td>

                        <td>
                            <%= student.date_of_birth %>
                        </td>

                        <td>
                            <%= link_to 'View' , student %>
                        </td>

                        <td>
                            <%= link_to 'Edit' , edit_student_path(student) %>
                        </td>
                        <td>
                            <%= link_to 'Delete' ,student ,method: :delete, data:{turbo_method: :delete,
                                turbo_confirm: "Are you sure?" } %>
                        </td>

                    </tr>
                    <% end %>
            </tbody>
        </table>

</div>

app/views/students/new.html.erb
<div class="col-lg-8">
    <h1>New Student</h1>

    <%= render "form" , student: @student %>

</div>

app/views/students/show.html.erb
<div class="col-lg-10">
    <p>
        <%= notice %>
    </p>

    <div class="card rounded-4 shadow">
        <div class="card-body">
            <h1>Student Details</h1>

    <p><strong>Name: </strong>
        <%= @student.full_name %>
    </p>

    <!-- <p><strong>First Name: </strong>
    <%= @student.first_name %>
</p>
<p><strong>Last Name: </strong>
    <%= @student.last_name %>
</p> -->
    <p><strong>Email: </strong>
        <%= @student.email %>
    </p>
    <p><strong>Adres: </strong>
        <%= @student.adress %>
    </p>

    <% if @student.date_of_birth.present? %>
        <p><strong>Date Of Birth: </strong>
            <%= formatted_date(@student.date_of_birth) %>
        </p>
        <% end %>



            <p><strong>Age: </strong>
                <%= @student.age %>
            </p>

            <%= link_to 'Back' , students_path, class: "btn btn-primary"%> |
                <%= link_to 'Edit' , edit_student_path(@student), class: "btn btn-secondary" %>

        </div>
      </div>

</div>